@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindExercisesCommandParser" as FindExercisesCommandParser LOGIC_COLOR
participant "f:FindExercisesCommand" as FindExercisesCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find_exercises bench")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("find_exercises bench")
activate AddressBookParser

create FindExercisesCommandParser
AddressBookParser -> FindExercisesCommandParser
activate FindExercisesCommandParser

FindExercisesCommandParser --> AddressBookParser
deactivate FindExercisesCommandParser

AddressBookParser -> FindExercisesCommandParser : parse("bench")
activate FindExercisesCommandParser

create FindExercisesCommand
FindExercisesCommandParser -> FindExercisesCommand
activate FindExercisesCommand

FindExercisesCommand --> FindExercisesCommandParser : f
deactivate FindExercisesCommand

FindExercisesCommandParser --> AddressBookParser : f
deactivate FindExercisesCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindExercisesCommandParser -[hidden]-> AddressBookParser
destroy FindExercisesCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FindExercisesCommand : execute()
activate FindExercisesCommand

FindExercisesCommand-> Model : updateFilteredExerciseList(predicate)
activate Model

Model --> FindExercisesCommand
deactivate Model

create CommandResult
FindExercisesCommand -> CommandResult
activate CommandResult

CommandResult --> FindExercisesCommand
deactivate CommandResult

FindExercisesCommand --> LogicManager : result
deactivate FindExercisesCommand

[<--LogicManager
deactivate LogicManager
@enduml
