@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFitNus <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class FitNus
Class ReadOnlyFitNus
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Exercise {
Class Exercise
Class Name
Class UniqueExerciseList
}

Package Routine {
Class Routine
Class Name
Class UniqueRoutineList
}

Package Lesson {
Class Lesson
Class Name
Class UniqueLessonList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FitNus .up.|> ReadOnlyFitNus

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" FitNus
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FitNus *--> "1" UniqueExerciseList
FitNus *--> "1" UniqueLessonList
UniqueExerciseList o--> "*" Exercise
Exercise *--> Name
Exercise *--> "*" Tag


FitNus *--> "1" UniqueRoutineList
UniqueRoutineList o--> "*" Routine
Routine --> "*" Exercise
ModelManager -->"1" Exercise : filtered list
@enduml
