@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class ExerciseListPanel
Class RoutineListPanel
Class LessonListPanel
Class RoutineCard
Class ExerciseCard
Class LessonCard
Class StatusBarFooter
Class CommandBox
Class HomePanel
Class TimetablePanel
Class SlotCard
Class SlotListPanel
Class CalorieGraph
Class BmiBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> HomePanel
MainWindow *-down-> TimetablePanel
MainWindow *-down-> CalorieGraph
MainWindow *-down-> BmiBox
HomePanel *-down-> ExerciseListPanel
HomePanel *-down-> RoutineListPanel
HomePanel *-down-> LessonListPanel
TimetablePanel *-down-> SlotListPanel
ExerciseListPanel -down-> ExerciseCard
RoutineListPanel -down-> RoutineCard
LessonListPanel -down-> LessonCard
SlotListPanel -down-> SlotCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
ExerciseCard --|> UiPart
RoutineCard --|> UiPart
LessonCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart

ExerciseCard ..> Model
RoutineCard ..> Model
LessonCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

ExerciseListPanel -[hidden]left- HelpWindow
RoutineListPanel -[hidden]left- HelpWindow
LessonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
